---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: eu-west-2
  version: "1.20"

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
